---
- hosts: all
  become: yes

  vars:
    app_dir: /home/vagrant/flask-project
    app_port: 8080

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-virtualenv
        state: present

    - name: Create a virtual environment
      pip:
        name: virtualenv
        executable: pip3

    - name: Create the application directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy the Flask application code
      copy:
        src: hello.py
        dest: "{{ app_dir }}/hello.py"

    - name: Create a virtual environment for the application
      virtualenv:
        path: "{{ app_dir }}/venv"
        python: python3

    - name: Install Flask and Gunicorn in the virtual environment
      pip:
        name:
          - flask
          - gunicorn
        virtualenv: "{{ app_dir }}/venv"

    - name: Start the Flask application with Gunicorn
      shell: |
        cd {{ app_dir }}
        source venv/bin/activate
        gunicorn --bind 0.0.0.0:{{ app_port }} hello:app
      async: 1000
      poll: 0

    - name: Ensure Gunicorn is running
      shell: ps aux | grep gunicorn
      register: gunicorn_status
      until: gunicorn_status.stdout.find("gunicorn") != -1
      retries: 3
      delay: 5

